[package]
name = "watch-list"
version = "0.2.0"
authors = ["Alexey Golubev <dr.freecx@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
serde_yaml = "0.9.27"
